name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Generate changelog
        id: changelog
        run: |
          # Get the latest two tags
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${CURRENT_TAG}^)
          
          # Generate changelog
          echo "## Changes" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log --pretty=format:"- %s" ${PREVIOUS_TAG}..${CURRENT_TAG} >> CHANGELOG.md
          
          # Set output for use in release
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Persian Connect ${{ github.ref }}
          body: |
            ## 🚀 Persian Connect Release ${{ github.ref }}
            
            ${{ steps.changelog.outputs.changelog }}
            
            ### 📦 Installation
            ```bash
            git clone https://github.com/ommzadeh/persian-connect.git
            cd persian-connect
            npm install
            ```
            
            ### 🚀 Quick Deploy
            - [Deploy to Vercel](https://vercel.com/new/clone?repository-url=https://github.com/ommzadeh/persian-connect)
            - [Deploy to Netlify](https://app.netlify.com/start/deploy?repository=https://github.com/ommzadeh/persian-connect)
            
            ### 📚 Documentation
            - [Deployment Guide](https://github.com/ommzadeh/persian-connect/blob/main/DEPLOYMENT_GUIDE.md)
            - [Contributing Guide](https://github.com/ommzadeh/persian-connect/blob/main/CONTRIBUTING.md)
            
            ---
            **Full Changelog**: https://github.com/ommzadeh/persian-connect/compare/${PREVIOUS_TAG}...${CURRENT_TAG}
          draft: false
          prerelease: false
          
  deploy-production:
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
          
      - name: Deploy to Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_ORG_ID }}