version: '3.8'

services:
  persian-connect:
    build: .
    container_name: persian-connect-app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.persian-connect.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.persian-connect.tls=true"
      - "traefik.http.routers.persian-connect.tls.certresolver=letsencrypt"